=== evemcd/wbs/javascript/uebungen/uebung21/kurse.dtd
<!ELEMENT kurse (kurs+)>
<!ELEMENT kurs (inhalt, dauer, vorraussetzung, beschreibung)>
<!ATTLIST kurs
          titel CDATA #REQUIRED>
<!ELEMENT inhalt (#PCDATA)>
<!ELEMENT dauer (#PCDATA)>
<!ELEMENT vorraussetzung (#PCDATA)>
<!ELEMENT beschreibung (#PCDATA)>

=== evemcd/wbs/javascript/uebungen/uebung21/kurse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kurse SYSTEM "kurse.dtd">
<kurse>
  <kurs titel="Webdeveloper">
    <inhalt>HTML, CSS, PHP, JavaScript, Typo3</inhalt>
    <dauer>121 Tage</dauer>
    <vorraussetzung>Realschulabschluss, Abitur, abgeschlossene Ausbildung</vorraussetzung>
    <beschreibung>Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden. Und weil Sie nun schon die Güte haben, mich ein paar weitere Sätze lang zu begleiten, möchte ich diese Gelegenheit nutzen, Ihnen nicht nur als Lückenfüller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards nämlich. Sehen Sie, Webstandards sind das Regelwerk, auf dem Webseiten aufbauen.</beschreibung>
  </kurs>
  <kurs titel="Java Programmer">
    <inhalt>Java, Oracle</inhalt>
    <dauer>121 Tage</dauer>
    <vorraussetzung>Realschulabschluss, Abitur, abgeschlossene Ausbildung</vorraussetzung>
    <beschreibung>Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden. Und weil Sie nun schon die Güte haben, mich ein paar weitere Sätze lang zu begleiten, möchte ich diese Gelegenheit nutzen, Ihnen nicht nur als Lückenfüller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards nämlich. Sehen Sie, Webstandards sind das Regelwerk, auf dem Webseiten aufbauen.</beschreibung>
  </kurs>
  <kurs titel="Webdesign">
    <inhalt>HTML, CSS, Photoshop, Illustrator, Wordpress</inhalt>
    <dauer>121 Tage</dauer>
    <vorraussetzung>Realschulabschluss, Abitur, abgeschlossene Ausbildung</vorraussetzung>
    <beschreibung>Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden. Und weil Sie nun schon die Güte haben, mich ein paar weitere Sätze lang zu begleiten, möchte ich diese Gelegenheit nutzen, Ihnen nicht nur als Lückenfüller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards nämlich. Sehen Sie, Webstandards sind das Regelwerk, auf dem Webseiten aufbauen.</beschreibung>
  </kurs>
  <kurs titel="Kommunikationsdesigner">
    <inhalt>Photoshop, Illustrator, Indesign, Gestaltungsgrundlagen</inhalt>
    <dauer>121 Tage</dauer>
    <vorraussetzung>Realschulabschluss, Abitur, abgeschlossene Ausbildung</vorraussetzung>
    <beschreibung>Überall dieselbe alte Leier. Das Layout ist fertig, der Text lässt auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines großen Bruders »Lorem Ipsum«, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen. Denn esse est percipi - Sein ist wahrgenommen werden. Und weil Sie nun schon die Güte haben, mich ein paar weitere Sätze lang zu begleiten, möchte ich diese Gelegenheit nutzen, Ihnen nicht nur als Lückenfüller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards nämlich. Sehen Sie, Webstandards sind das Regelwerk, auf dem Webseiten aufbauen.</beschreibung>
  </kurs>
</kurse>
