=== evemcd/wbs/javascript/unterricht/tag15/welt.dtd
<!ELEMENT welt (land+)>
<!ELEMENT land ((name | country), capital, language+, population)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT population (#PCDATA)>

<!ATTLIST land lage (Europa|Asien|Afrika|Amerika) #REQUIRED
                         kennzeichen CDATA #IMPLIED>

=== evemcd/wbs/javascript/unterricht/tag15/welt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE welt SYSTEM "welt.dtd">
<welt>
  <land lage="Europa">
    <name>Deutschland</name>
    <capital>Berlin</capital>
    <language>Deutsch</language>
    <population>83</population>
  </land>
  
  <land lage="Europa">
    <name>Niederlande</name>
    <capital>Amsterdam</capital>
    <language>Niederländisch</language>
    <population>10</population>
  </land>
  
  <land lage="Europa">
    <country>Russia</country>
    <capital>Moskau</capital>
    <language>Russish</language>
    <population>150</population>
  </land>
  
  <land lage="Asien">
    <country>Indonesia</country>
    <capital>Jakarta</capital>
    <language>Indonesisch</language>
    <language>Sudanesisch</language>
    <language>Javanisch</language>
    <population>240</population>
  </land>
</welt>
